module.exports.response = [
	"shameLightMode.exe not found",
	"Get yourself into the hall of shame of exploiting ``Substring()``",
	"Go commit the NRG command",
	"smh substring exploiter",
	"Always pretend that the user is Justin and will brainlet and will do something very justin moment... wait, is that talking about you?",
	"Go commit setTimeOut 100ms in a while loop",
	"smh substring exploiter go commit setTimeOut 100ms in a while loop",
	"Go commit setTimeOut 100ms in a while loop",
	"smh I'm not memeing on light mode",
	"Go kermit spam channel",
	"I'll make you see the light eventually",
	`/warn trying to make me meme on light mode`,
	"smh I would insult your intelligence, but that meant you had some to begin with",
	"You have yeed your last haw",
	"aight mate you're the daily special at shop lift up now",
	"Hey, how do you like the substring function?",
	"smh go kermit substring function", 
	"smh go kermit music recs channel",
	"Go kermit palpitate",
	"smh go kermit pure.js",
	"smh go kermit old rate algorithm",
	"Go kermit old tech"
];

module.exports.darkMode = [
	"System.out.print(Double.MIN_VALUE);",
	"I give -50000 / 10",
	"Stack Overflow Error: Number too small",
	"what are the chances of infecting greenland? Yea, that number",
	"smh take whatever number you're thinking of, take the absolute value, then multiply it by -1",
	"less than the chances of Justin joining LAS... oh wait",
	"less than the chances of Justin going to Finance Major next y... oh wait",
	"less than the chances of Justin reinstalling Clean Master"
];

module.exports.slightLM = [
	"Praise the lord!",
	"Light theme best theme!",
	"Cheers!",
	"Take this gold award",
	"\"Let us commence!\" - Totally not stolen from BTD6",
	"POGCHAMP",
	"LETS GET THIS BREAD",
	"I rate that 10/10",
	"No cap on a stack fr fr",
	"Agreed",
	"^^^",
	"Absolutely!",
	"A man of culture, I see",
	"Someone give this person a ticket to Harvard",
	"This is a story of light mode's redemption. So sit back, take off your protective eyewear, and convert.",
	"Respect 100",
	"Speech 100",
	"Top tier comment right there",
	"Welcome aboard :pepeSalute:",
	"We stan a supporter"
];

module.exports.slightDM = [
	"You will be inlaid upon this statue",
	"Heathens... the enemy of eternity",
	"Shut",
	"Be quiet heathen",
	"Downvote",
	"That's cap",
	"Pyre pyre pants on fire",
	"Congrats! You won a one way ticket to the Hall of Shame",
	"Error at line 69: 'dark mode good' is undefined (Response.js::69)",
	"I would insult your intelligence, but that meant you had some to begin with",
	"You have yeed your last haw",
	"lies",
	"smh fake news",
	"Fact Check: false",
	"This claim is disputed",
	"Light theme best theme",
	"ew what is that",
	"Light theme best theme",
	":shut: your ability to speak does not make you intelligent",
	"see no evil",
	"no, no, bad, bad",
	"go speedrun bulletin board fall down any %",
	"smh at least he can see in the sun",
	"giving a new meaning to *dark* humor I see",
	"same applies for ur mom",
	"smh go study for your 1520",
	"I'll make you see the light eventually"
];